import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Head1 from './components/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Head1 />
        {children}
      <h1> ------------- End RootLayout ------------ </h1>
      </body>
    </html>
  )
}
